Repository BinaryStudioAcademy/bsa-2021-hypecrafter, pull requests merged in 2021-09, with the labels that each got.

#172 Add more social integrations at UserProfile
  backend/src/data/entities/userProfile.ts
  backend/src/data/migrations/1630317620149-add-new-social-links.ts
  backend/src/data/seed-data/userProfileData.ts
  frontend/src/common/types/userProfile/userProfile.ts
  frontend/src/scenes/UserPage/components/Header.tsx
  frontend/src/scenes/UserPage/styles.module.scss
Labels: enhancement

#176 Add social media sharing links/buttons on the project page
  frontend/package.json
  frontend/src/components/ShareProjectModal/index.tsx
  frontend/src/components/ShareProjectModal/styles.module.scss
  frontend/src/scenes/ProjectPage/components/Header.tsx
  frontend/src/scenes/ProjectPage/styles.module.scss
Labels: enhancement

#160 Update tabs
  frontend/src/common/enums/mark.ts
  frontend/src/common/types/project/index.ts
  frontend/src/components/ProjectInfo/index.tsx
  frontend/src/components/ProjectInfo/styles.module.scss
  frontend/src/components/Tabs/Tab/index.tsx
  frontend/src/components/Tabs/TabTitle/index.tsx
  frontend/src/components/Tabs/Tabs/index.tsx
  frontend/src/components/Tabs/styles.module.scss
  frontend/src/scenes/ProjectPage/components/Header.tsx
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/reducer.ts
  frontend/src/scenes/ProjectPage/styles.module.scss
  frontend/src/styles/_mixins.scss
Labels: enhancement

#183 Add meta data
  frontend/public/index.html
  frontend/public/manifest.json
Labels: enhancement

#186 fix userId in req headers
  gateway/src/api/middlewares/setUserInfo.ts
  shared/src/common/types/types.d.ts
Labels: fix

#190 delete global styles
  frontend/src/scenes/UserPage/styles.module.scss
Labels: hotfix

#187 Add hypecoin icon to project info
  frontend/src/components/ProjectInfo/index.tsx
  frontend/src/components/ProjectInfo/styles.module.scss
Labels: enhancement

#174 feat/multiselect-component-for-categories
  backend/package-lock.json
  backend/src/api/routes/project.ts
  backend/src/data/repositories/project.ts
  backend/src/services/project/project.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/index.ts
  frontend/src/components/MultiSelect/index.tsx
  frontend/src/components/MultiSelect/styles.module.scss
  frontend/src/components/MultiSelect/styles.scss
  frontend/src/components/Select/index.tsx
  frontend/src/components/UserModal/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/helpers/runActionWithValueOfEnum.ts
  frontend/src/hooks/useQuery.ts
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/Projects/actions.ts
  frontend/src/scenes/Projects/components/Filters/index.tsx
  frontend/src/scenes/Projects/index.tsx
  frontend/src/scenes/Projects/reducer.ts
  frontend/src/scenes/Wallet/Payment/components/SuccessPage/styles.module.scss
  frontend/src/services/projects.ts
  gateway/package-lock.json
  notification/package-lock.json
  package-lock.json
  payment/package-lock.json
  shared/package-lock.json
  shared/src/common/enums/projectFilters.ts
Labels: enhancement

#184 migration payments from PostgreSQL to MongoDB
  frontend/package-lock.json
  package.json
  payment/.env.example
  payment/package-lock.json
  payment/package.json
  payment/src/api/routes/payment.ts
  payment/src/common/types/payment/payment.ts
  payment/src/data/db/.gitkeep
  payment/src/data/db/createConnection.ts
  payment/src/data/entities/abstract.ts
  payment/src/data/entities/transactionHistory.ts
  payment/src/data/migrations/1627805421872-AddTransaction.ts
  payment/src/data/migrations/1628690647941-RenameTableAndChangeColumn.ts
  payment/src/data/migrations/1630355991986-DeleteBalance.ts
  payment/src/data/models/payment.ts
  payment/src/data/repositories/index.ts
  payment/src/data/repositories/payment.ts
  payment/src/data/repositories/transactionHistory.ts
  payment/src/data/seed-data/paymentData.ts
  payment/src/data/seeders/.gitkeep
  payment/src/data/seeders/index.ts
  payment/src/data/seeders/paymentSeeder.ts
  payment/src/data/seeders/transactionHistorySeeder.ts
  payment/src/env.ts
  payment/src/helpers/env.ts
  payment/src/helpers/request.ts
  payment/src/server.ts
  payment/src/services/index.ts
  payment/src/services/payment/payment.ts
  shared/src/common/helpers/index.ts
Labels: enhancement

#179 Feat/add notifications popover
  frontend/src/common/enums/notifications.ts
  frontend/src/common/types/notification/index.ts
  frontend/src/common/types/notification/notification.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Notification/index.tsx
  frontend/src/components/Notification/styles.module.scss
  frontend/src/components/NotificationsPopover/index.tsx
  frontend/src/components/NotificationsPopover/styles.module.scss
  frontend/src/components/Popover/styles.module.scss
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
Labels: enhancement

#177 Fix backend problems
  backend/src/api/routes/auth.ts
  backend/src/data/repositories/user.ts
  backend/src/services/user/user.ts
  frontend/package.json
  frontend/src/common/types/user/user.ts
  frontend/src/common/types/userProfile/userProfile.ts
  frontend/src/components/Routing/index.tsx
  frontend/src/helpers/http.ts
  gateway/src/api/middlewares/saveReqBodyUserEmail.ts
  gateway/src/api/passport/index.ts
  gateway/src/api/routes/auth.ts
  gateway/src/common/constants/blackRoutes.ts
  gateway/src/common/types/global.d.ts
Labels: hotfix

#195 fix http helper
  frontend/src/helpers/http.ts
Labels: hotfix

#191 Feat/mobile main page
  mobile/HypecrafterMobile/app/App.tsx
  mobile/HypecrafterMobile/app/actions/index.ts
  mobile/HypecrafterMobile/app/common/enums/category/category.ts
  mobile/HypecrafterMobile/app/common/enums/category/index.ts
  mobile/HypecrafterMobile/app/common/enums/index.ts
  mobile/HypecrafterMobile/app/common/enums/projects/index.ts
  mobile/HypecrafterMobile/app/common/enums/projects/projectsCategories.ts
  mobile/HypecrafterMobile/app/common/enums/projects/projectsFilter.ts
  mobile/HypecrafterMobile/app/common/enums/projects/projectsSort.ts
  mobile/HypecrafterMobile/app/common/types/comment/comment.ts
  mobile/HypecrafterMobile/app/common/types/comment/index.ts
  mobile/HypecrafterMobile/app/common/types/index.tsx
  mobile/HypecrafterMobile/app/common/types/project/index.ts
  mobile/HypecrafterMobile/app/common/types/project/mark.ts
  mobile/HypecrafterMobile/app/common/types/project/project.ts
  mobile/HypecrafterMobile/app/common/types/project/projectPrivileges.ts
  mobile/HypecrafterMobile/app/common/types/store/state.ts
  mobile/HypecrafterMobile/app/common/types/topic/index.ts
  mobile/HypecrafterMobile/app/common/types/topic/topic.ts
  mobile/HypecrafterMobile/app/components/MainView/MainView.tsx
  mobile/HypecrafterMobile/app/components/MainView/actions.ts
  mobile/HypecrafterMobile/app/components/MainView/reducer.ts
  mobile/HypecrafterMobile/app/components/MainView/sagas.ts
  mobile/HypecrafterMobile/app/components/MainView/screens/ProjectsScreen.tsx
  mobile/HypecrafterMobile/app/components/common/ProjectCard.tsx
  mobile/HypecrafterMobile/app/components/common/Tag.tsx
  mobile/HypecrafterMobile/app/reducers/index.ts
  mobile/HypecrafterMobile/app/sagas/index.ts
  mobile/HypecrafterMobile/app/services/projects.ts
  mobile/HypecrafterMobile/app/services/topics.ts
  mobile/HypecrafterMobile/app/styles/common.ts
  mobile/HypecrafterMobile/package.json
Labels: enhancement

#189 Add login view
  frontend/src/services/project.ts
  mobile/HypecrafterMobile/android/app/build.gradle
  mobile/HypecrafterMobile/app/App.tsx
  mobile/HypecrafterMobile/app/actions/index.ts
  mobile/HypecrafterMobile/app/actions/login.ts
  mobile/HypecrafterMobile/app/assets/images/HypeCoin.png
  mobile/HypecrafterMobile/app/assets/images/HypeCrafter.png
  mobile/HypecrafterMobile/app/assets/images/login_bg.jpg
  mobile/HypecrafterMobile/app/common/constants/index.ts
  mobile/HypecrafterMobile/app/common/constants/storageKey.ts
  mobile/HypecrafterMobile/app/common/enums/index.ts
  mobile/HypecrafterMobile/app/common/enums/user/user-authorization-key.ts
  mobile/HypecrafterMobile/app/common/styles/colors.ts
  mobile/HypecrafterMobile/app/common/styles/mixins.ts
  mobile/HypecrafterMobile/app/common/types/index.tsx
  mobile/HypecrafterMobile/app/common/types/signup/index.ts
  mobile/HypecrafterMobile/app/common/types/signup/signup.ts
  mobile/HypecrafterMobile/app/common/types/store/state.ts
  mobile/HypecrafterMobile/app/components/LoginView/LoginView.tsx
  mobile/HypecrafterMobile/app/components/MainView/MainView.tsx
  mobile/HypecrafterMobile/app/helpers/http.ts
  mobile/HypecrafterMobile/app/reducers/index.ts
  mobile/HypecrafterMobile/app/reducers/login.ts
  mobile/HypecrafterMobile/app/sagas/index.ts
  mobile/HypecrafterMobile/app/sagas/login.ts
  mobile/HypecrafterMobile/app/services/login.ts
  mobile/HypecrafterMobile/package-lock.json
  mobile/HypecrafterMobile/package.json
  mobile/HypecrafterMobile/yarn.lock
Labels: enhancement

#192 Add statistics block and generate reports in frontend
  backend/src/api/routes/project.ts
  backend/src/common/enums/index.ts
  backend/src/common/types/project/index.ts
  backend/src/common/types/project/statistics.ts
  backend/src/data/repositories/project.ts
  backend/src/services/project/project.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/index.ts
  frontend/src/common/types/project/statistics.ts
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/ProjectPage/actions.ts
  frontend/src/scenes/ProjectPage/components/Statistics/Card/index.tsx
  frontend/src/scenes/ProjectPage/components/Statistics/Card/style.module.scss
  frontend/src/scenes/ProjectPage/components/Statistics/TimeButton/TimeButton.tsx
  frontend/src/scenes/ProjectPage/components/Statistics/TimeButton/style.module.scss
  frontend/src/scenes/ProjectPage/components/Statistics/helper.ts
  frontend/src/scenes/ProjectPage/components/Statistics/index.tsx
  frontend/src/scenes/ProjectPage/components/Statistics/options.ts
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/interfaces.ts
  frontend/src/scenes/ProjectPage/reducer.ts
  frontend/src/scenes/ProjectPage/sagas.ts
  frontend/src/scenes/ProjectPage/styles.module.scss
  frontend/src/services/project.ts
  gateway/src/api/routes/project.ts
  shared/src/common/enums/index.ts
  shared/src/common/enums/timeInterval.ts
Labels: enhancement

#203 Feat/mobile header
  mobile/HypecrafterMobile/app/components/common/Header.tsx
  mobile/HypecrafterMobile/app/routes/StackNavigation/AppNavigator.tsx
Labels: enhancement

#185 featuer donators team chat
  frontend/src/components/Chat/ChatContent.tsx
  frontend/src/components/Chat/MessageInterface.ts
  frontend/src/components/Chat/helpers.ts
  frontend/src/components/Chat/index.tsx
  frontend/src/components/Chat/styles.module.scss
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
Labels: enhancement

#205 Add use balance
  frontend/src/components/Header/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useBalance.ts
  frontend/src/scenes/Wallet/FundsPage/index.tsx
  frontend/src/scenes/Wallet/FundsPage/styles.module.scss
Labels: hotfix

#208 Feat/recommendation system on project creation
  backend/package-lock.json
  backend/package.json
  backend/src/api/routes/project.ts
  backend/src/common/constans/index.ts
  backend/src/common/constans/timeInterval/index.ts
  backend/src/common/types/project/index.ts
  backend/src/common/types/project/recommendedProject.ts
  backend/src/data/repositories/category.ts
  backend/src/data/repositories/project.ts
  backend/src/data/repositories/tag.ts
  backend/src/services/index.ts
  backend/src/services/project/project.ts
  frontend/src/actions/index.ts
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/CreateProject/actions.ts
  frontend/src/scenes/CreateProject/components/Layout/index.tsx
  frontend/src/scenes/CreateProject/components/RecommendationCard/index.tsx
  frontend/src/scenes/CreateProject/components/RecommendationCard/styles.module.scss
  frontend/src/scenes/CreateProject/components/Recommendations/index.tsx
  frontend/src/scenes/CreateProject/components/Recommendations/styles.module.scss
  frontend/src/scenes/CreateProject/components/Settings/index.tsx
  frontend/src/scenes/CreateProject/enums/curentPages.ts
  frontend/src/scenes/CreateProject/index.tsx
  frontend/src/scenes/CreateProject/reducer.ts
  frontend/src/scenes/CreateProject/sagas.ts
  frontend/src/scenes/CreateProject/types.ts
  frontend/src/services/projects.ts
  frontend/src/styles/_vars.scss
  gateway/src/api/routes/project.ts
Labels: enhancement

#201 Feature upcoming projects page
  backend/src/api/routes/project.ts
  backend/src/data/repositories/project.ts
  backend/src/services/project/project.ts
  frontend/package.json
  frontend/src/actions/index.ts
  frontend/src/components/Header/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/Projects/actions.ts
  frontend/src/scenes/Projects/components/Filters/index.tsx
  frontend/src/scenes/Projects/components/Filters/styles.module.scss
  frontend/src/scenes/Projects/index.tsx
  frontend/src/scenes/Projects/reducer.ts
  frontend/src/scenes/UserPage/components/Header.tsx
  frontend/src/services/projects.ts
  shared/src/common/enums/projectFilters.ts
Labels: enhancement

#194 Feature interaction time count of views
  backend/src/api/routes/auth.ts
  backend/src/api/routes/project.ts
  backend/src/common/types/project/index.ts
  backend/src/common/types/project/project.ts
  backend/src/common/types/project/updateInteractionTime.ts
  backend/src/common/types/project/updateViewsAndInteractionTime.ts
  backend/src/data/mappers/index.ts
  backend/src/data/mappers/mapBoolean.ts
  backend/src/data/mappers/mapProjects.ts
  backend/src/data/mappers/nullToNumber.ts
  backend/src/data/repositories/project.ts
  backend/src/services/project/project.ts
  backend/src/services/user/user.ts
  frontend/.eslintrc.json
  frontend/src/actions/index.ts
  frontend/src/common/types/index.tsx
  frontend/src/common/types/project/project.ts
  frontend/src/common/types/user/user.ts
  frontend/src/common/types/userProfile/userProfile.ts
  frontend/src/common/types/viewsAndInteractionTime/index.ts
  frontend/src/common/types/viewsAndInteractionTime/viewsAndInteractionTimeQuery.ts
  frontend/src/common/types/viewsAndInteractionTime/viewsAndInteractionTimeResponse.ts
  frontend/src/components/ImageUpload/index.tsx
  frontend/src/components/Link/index.tsx
  frontend/src/components/ProjectInfo/index.tsx
  frontend/src/components/Routing/index.tsx
  frontend/src/components/ShareProjectModal/index.tsx
  frontend/src/components/Tabs/Tab/index.tsx
  frontend/src/components/Tabs/TabTitle/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/helpers/http.ts
  frontend/src/hooks/useCountTimeOnPage.ts
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/CreateProject/components/Funding/index.tsx
  frontend/src/scenes/CreateProject/components/Layout/index.tsx
  frontend/src/scenes/CreateProject/components/Settings/index.tsx
  frontend/src/scenes/ProjectPage/components/Header.tsx
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/reducer.ts
  frontend/src/scenes/Projects/actions.ts
  frontend/src/scenes/Projects/reducer.ts
  frontend/src/scenes/Projects/sagas.ts
  frontend/src/services/projects.ts
  gateway/src/api/middlewares/saveReqBodyUserEmail.ts
  gateway/src/api/routes/auth.ts
  gateway/src/api/routes/project.ts
  gateway/src/common/types/global.d.ts
Labels: enhancement

#209 Add project tabs info
  mobile/HypecrafterMobile/app/components/ProjectView/ProjectView.tsx
  mobile/HypecrafterMobile/app/components/ProjectView/screens/Comments.tsx
  mobile/HypecrafterMobile/app/components/ProjectView/screens/FAQ.tsx
  mobile/HypecrafterMobile/app/components/common/Accordion.tsx
  mobile/HypecrafterMobile/app/exports.d.ts
  mobile/HypecrafterMobile/app/routes/StackNavigation/AppNavigator.tsx
  mobile/HypecrafterMobile/package-lock.json
  mobile/HypecrafterMobile/package.json
  mobile/HypecrafterMobile/yarn.lock
Labels: enhancement

#210 Fix word
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
Labels: fix

#211 Add story
  mobile/HypecrafterMobile/android/app/src/main/java/com/hypecraftermobile/MainApplication.java
  mobile/HypecrafterMobile/android/settings.gradle
  mobile/HypecrafterMobile/app/components/ProjectView/ProjectView.tsx
  mobile/HypecrafterMobile/app/components/ProjectView/screens/Story.tsx
  mobile/HypecrafterMobile/app/components/common/Accordion.tsx
  mobile/HypecrafterMobile/app/exports.d.ts
  mobile/HypecrafterMobile/ios/Podfile
  mobile/HypecrafterMobile/package-lock.json
  mobile/HypecrafterMobile/package.json
  mobile/HypecrafterMobile/yarn.lock
Labels: enhancement

#212 Add error message and block ability to send empty comment
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/ProjectPage/components/Comments.tsx
Labels: fix

#214 Add apk build depenedecies
  mobile/HypecrafterMobile/android/app/build.gradle
  mobile/HypecrafterMobile/android/gradle.properties
Labels: enhancement

#217 Fix mobile app and add useAuth
  mobile/HypecrafterMobile/app/App.tsx
  mobile/HypecrafterMobile/app/components/Main.tsx
  mobile/HypecrafterMobile/app/components/ProjectView/ProjectView.tsx
  mobile/HypecrafterMobile/app/components/UserView/UserView.tsx
  mobile/HypecrafterMobile/app/helpers/http.ts
  mobile/HypecrafterMobile/app/hooks/useAuth.ts
  mobile/HypecrafterMobile/app/storage.ts
Labels: enhancement

#181 Edit ProjectCard
  frontend/src/components/ProjectCard/index.tsx
  frontend/src/components/ProjectCard/styles.module.scss
Labels: hotfix

#221 Some mobile fixes
  mobile/HypecrafterMobile/app/components/LoginView/LoginView.tsx
  mobile/HypecrafterMobile/app/components/MainView/screens/ProjectsScreen.tsx
  mobile/HypecrafterMobile/app/components/ProjectView/ProjectView.tsx
  mobile/HypecrafterMobile/app/components/common/ProgressBar.tsx
Labels: fix

#224 Add balance to request current user.
  backend/src/data/repositories/user.ts
Labels: hotfix

#225 Fix infinity loading and return UserProfile with balance
  backend/src/data/repositories/user.ts
  backend/src/services/user/user.ts
Labels: hotfix

#227 Add first and lastName to avatar.
  frontend/src/common/types/user/user.ts
  frontend/src/components/Header/index.tsx
Labels: hotfix

#229 Add real user id for open user profile.
  frontend/src/components/OpenUserModalOption/index.tsx
Labels: hotfix

#231 Feat/donate frontend
  backend/src/api/routes/donate.ts
  backend/src/data/repositories/donate.ts
  backend/src/data/repositories/user.ts
  backend/src/services/donate/donate.ts
  frontend/src/actions/index.ts
  frontend/src/common/types/store/state.ts
  frontend/src/components/ProjectInfo/index.tsx
  frontend/src/components/Routing/index.tsx
  frontend/src/components/SelectedFund/index.tsx
  frontend/src/components/SelectedFund/styles.module.scss
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Donate/actions.ts
  frontend/src/scenes/Donate/component/failure/failure.tsx
  frontend/src/scenes/Donate/component/startPage/startPage.tsx
  frontend/src/scenes/Donate/component/success/success.tsx
  frontend/src/scenes/Donate/index.tsx
  frontend/src/scenes/Donate/reducer.ts
  frontend/src/scenes/Donate/sagas.ts
  frontend/src/scenes/Donate/styles.module.scss
  frontend/src/scenes/Wallet/Payment/components/SuccessPage/index.tsx
  frontend/src/scenes/Wallet/Payment/index.tsx
  frontend/src/services/donate.ts
  payment/src/api/routes/payment.ts
Labels: enhancement

#233 Feat/chat sockets
  backend/src/api/routes/chat.ts
  backend/src/api/routes/index.ts
  backend/src/common/enums/path.ts
  backend/src/data/entities/message.ts
  backend/src/data/migrations/1631228689838-addChatIdAndAuthorIdColumnToMessageTable.ts
  backend/src/data/repositories/index.ts
  backend/src/data/repositories/message.ts
  backend/src/services/chat/chat.ts
  backend/src/services/chat/index.ts
  backend/src/services/index.ts
  frontend/src/common/enums/socketActions.ts
  frontend/src/components/Header/index.tsx
  frontend/src/providers/sockets.tsx
  gateway/package-lock.json
  gateway/package.json
  gateway/src/api/middlewares/index.ts
  gateway/src/api/routes/chat.ts
  gateway/src/api/routes/index.ts
  gateway/src/common/enums/actionsPath.ts
  gateway/src/common/enums/path.ts
  gateway/src/common/enums/socketActions.ts
  gateway/src/services/socketController.ts
Labels: in progress

#236 Add production seeds
  backend/package.json
  backend/src/data/seed-data-production/categoryData.ts
  backend/src/data/seed-data-production/tagsData.ts
  backend/src/data/seed-data-production/userProfileData.ts
  backend/src/data/seeders-production/categorySeeder.ts
  backend/src/data/seeders-production/index.ts
  backend/src/data/seeders-production/tagsSeeder.ts
  backend/src/data/seeders-production/userProfileSeeder.ts
  gateway/package.json
  gateway/src/data/seed-data-production/userData.ts
  gateway/src/data/seeders-production/index.ts
  gateway/src/data/seeders-production/userSeeder.ts
  package.json
Labels: enhancement

#239 Fix project Page style
  backend/src/common/types/project/project.ts
  backend/src/data/repositories/project.ts
  frontend/src/common/constans/colors/projectPage.ts
  frontend/src/common/types/project/project.ts
  frontend/src/scenes/ProjectPage/components/Header.tsx
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/styles.module.scss
Labels: enhancement
