Repository BinaryStudioAcademy/bsa-2021-hypecrafter, pull requests merged in 2021-08, with the labels that each got.

#23 Create modal window
  frontend/src/components/Main/index.tsx
  frontend/src/components/ModalWindow/index.tsx
  frontend/src/components/ModalWindow/modal.scss
Labels: enhancement

#25 add login page
  frontend/src/assets/HypeCrafter.svg
  frontend/src/assets/login_bg.jpg
  frontend/src/common/enums/routes.ts
  frontend/src/components/LoginPage/index.tsx
  frontend/src/components/LoginPage/styles.module.scss
  frontend/src/components/Routing/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/styles/_mixins.scss
  frontend/src/styles/_vars.scss
Labels: enhancement

#18 Add payment microservice.
  backend/src/data/entities/donate.ts
  backend/src/data/entities/userProfile.ts
  backend/src/data/migrations/1627670468517-addDonate.ts
  gateway/package-lock.json
  package.json
  payment/.env.development
  payment/package-lock.json
  payment/package.json
  payment/src/api/routes/index.ts
  payment/src/api/routes/payment.ts
  payment/src/common/enums/index.ts
  payment/src/common/enums/path.ts
  payment/src/common/types/global.d.ts
  payment/src/common/types/index.ts
  payment/src/common/types/payment/index.ts
  payment/src/common/types/payment/payment.ts
  payment/src/data/db/.gitkeep
  payment/src/data/entities/abstract.ts
  payment/src/data/entities/transaction.ts
  payment/src/data/mappers/.gitkeep
  payment/src/data/migrations/1627805421872-AddTransaction.ts
  payment/src/data/repositories/index.ts
  payment/src/data/repositories/transaction.ts
  payment/src/data/seeds/.gitkeep
  payment/src/env.ts
  payment/src/helpers/env.ts
  payment/src/helpers/index.ts
  payment/src/helpers/logger.ts
  payment/src/helpers/request.ts
  payment/src/server.ts
  payment/src/services/index.ts
  payment/src/services/payment/index.ts
  payment/src/services/payment/payment.ts
  payment/tsconfig.json
Labels: enhancement

#20 add Card component
  frontend/src/components/Card/CardWithLink.tsx
  frontend/src/components/Card/index.tsx
  frontend/src/components/Card/styles.module.scss
  frontend/src/components/CardExample/index.tsx
  frontend/src/components/CardExample/styles.module.scss
  frontend/src/components/Link/index.tsx
  frontend/src/components/Link/styles.module.scss
  frontend/src/components/Main/index.tsx
  frontend/src/components/ProgressBar/index.tsx
  frontend/src/components/ProgressBar/styles.module.scss
  frontend/src/components/ProjectCard/index.tsx
  frontend/src/components/ProjectCard/styles.module.scss
  frontend/src/components/Tag/index.tsx
  frontend/src/components/Tag/styles.module.scss
Labels: enhancement

#39 Add mixins for typography
  frontend/src/components/Main/index.tsx
  frontend/src/components/TextStyleExample/index.tsx
  frontend/src/components/TextStyleExample/styles.module.scss
  frontend/src/styles/_mixins.scss
  frontend/src/styles/_vars.scss
Labels: enhancement

#42 implement react hook form to login page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Input/index.tsx
  frontend/src/components/InputExample/index.tsx
  frontend/src/components/LoginPage/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
Labels: enhancement

#36 Add funds page
  frontend/src/common/enums/routes.ts
  frontend/src/components/Routing/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/Wallet/CustomFund/index.tsx
  frontend/src/scenes/Wallet/CustomFund/styles.module.scss
  frontend/src/scenes/Wallet/Fund/index.tsx
  frontend/src/scenes/Wallet/Fund/styles.module.scss
  frontend/src/scenes/Wallet/FundsPage/index.tsx
  frontend/src/scenes/Wallet/FundsPage/styles.module.scss
  frontend/src/styles/_vars.scss
Labels: enhancement

#56 add animated counter
  frontend/src/components/Counter/ExampleCounter.tsx
  frontend/src/components/Counter/helpers.ts
  frontend/src/components/Counter/index.tsx
  frontend/src/components/Counter/styles.module.scss
  frontend/src/components/Main/index.tsx
Labels: enhancement

#75 replace `copy` with `cp` in build script
  shared/package.json
Labels: invalid

#63 Connect User Page to the Backend
  backend/package-lock.json
  backend/src/api/routes/user.ts
  backend/src/common/types/user/user.ts
  backend/src/data/entities/userProfile.ts
  backend/src/data/migrations/1628360157794-AddTables.ts
  backend/src/data/migrations/1628407165448-UpdateRelations.ts
  backend/src/data/migrations/1628598112903-UpdateUserProfileEntity.ts
  backend/src/data/seed-data/userProfileData.ts
  docker-compose.rabbitmq.yml
  frontend/package-lock.json
  frontend/src/common/types/index.tsx
  frontend/src/common/types/store/state.ts
  frontend/src/common/types/userProfile/index.ts
  frontend/src/common/types/userProfile/userProfile.ts
  frontend/src/components/BootstrapExample/index.tsx
  frontend/src/components/Main/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/UserPage/actions.ts
  frontend/src/scenes/UserPage/components/Body.tsx
  frontend/src/scenes/UserPage/components/Header.tsx
  frontend/src/scenes/UserPage/index.tsx
  frontend/src/scenes/UserPage/interfaces.ts
  frontend/src/scenes/UserPage/reducer.ts
  frontend/src/scenes/UserPage/sagas.ts
  frontend/src/scenes/UserPage/styles.module.scss
  frontend/src/services/users.ts
  gateway/package-lock.json
  gateway/src/api/middlewares/authorization.ts
  gateway/src/common/constants/whiteRouts.ts
  gateway/src/helpers/uuid.ts
  notification/package-lock.json
  package.json
  payment/package-lock.json
  resources/.eslintrc.json
  resources/gulpfile.js
  resources/src/helpers/getData.js
  shared/package-lock.json
Labels: enhancement

#55 Add useAction hook
  frontend/src/actions/index.ts
  frontend/src/components/Routing/index.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/useAction.ts
  frontend/src/scenes/UserPage/index.tsx
Labels: enhancement

#76 Add mixin with hoover effects.
  frontend/src/styles/_mixins.scss
Labels: enhancement

#74 Feature use auth hook
  frontend/src/hooks/index.ts
  frontend/src/hooks/useAuth.ts
  package.json
Labels: enhancement

#79 fix array helper
  shared/src/common/helpers/arrayHelper.ts
Labels: invalid

#73 Add trends page (Frontend)
  deploy-staging.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Chart/helpers.ts
  frontend/src/components/Chart/index.tsx
  frontend/src/components/Routing/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/helpers/array.ts
  frontend/src/helpers/bright-colors.ts
  frontend/src/helpers/index.ts
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/TrendsPage/components/ProjectsChart/CategorySubtitle/index.tsx
  frontend/src/scenes/TrendsPage/components/ProjectsChart/CategorySubtitle/style.module.scss
  frontend/src/scenes/TrendsPage/components/ProjectsChart/index.tsx
  frontend/src/scenes/TrendsPage/components/ProjectsChart/style.module.scss
  frontend/src/scenes/TrendsPage/components/TagsChart/index.tsx
  frontend/src/scenes/TrendsPage/components/TagsChart/style.module.scss
  frontend/src/scenes/TrendsPage/components/index.ts
  frontend/src/scenes/TrendsPage/data.ts
  frontend/src/scenes/TrendsPage/index.tsx
  frontend/src/scenes/TrendsPage/interfaces.ts
  frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
  frontend/src/scenes/TrendsPage/options/TagsOptions.ts
  frontend/src/scenes/TrendsPage/options/index.ts
  frontend/src/scenes/TrendsPage/styles.module.scss
  package-lock.json
  package.json
Labels: enhancement

#69 Change type of swagger file from JSON to YALM
  gateway/openApiDocumentation.json
  gateway/openApiDocumentation.yaml
  gateway/package-lock.json
  gateway/package.json
  gateway/src/api/middlewares/index.ts
Labels: enhancement

#86 add useScroll hook
  frontend/src/hooks/index.ts
  frontend/src/hooks/useScroll.ts
Labels: enhancement

#82 add "switch language" option
  frontend/src/components/Header/index.tsx
  frontend/src/components/SwitchLanguageOption/LanguageSwitcher.tsx
  frontend/src/components/SwitchLanguageOption/styles.module.scss
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
Labels: enhancement

#83 Feat/transictions page backend
  gateway/openApiDocumentation.yaml
  gateway/package-lock.json
  gateway/src/api/middlewares/index.ts
  gateway/src/api/routes/auth.ts
  gateway/src/api/routes/index.ts
  gateway/src/api/routes/payment.ts
  gateway/src/common/constants/whiteRouts.ts
  gateway/src/common/enums/path.ts
  package-lock.json
  payment/package-lock.json
  payment/src/api/routes/payment.ts
  payment/src/common/enums/path.ts
  payment/src/common/types/payment/payment.ts
  payment/src/data/entities/transaction.ts
  payment/src/data/entities/transactionHistory.ts
  payment/src/data/migrations/1627805421872-AddTransaction.ts
  payment/src/data/migrations/1628690647941-RenameTableAndChangeColumn.ts
  payment/src/data/repositories/index.ts
  payment/src/data/repositories/transaction.ts
  payment/src/data/repositories/transactionHistory.ts
  payment/src/data/seed-data/transactionHistoryData.ts
  payment/src/data/seeders/.gitkeep
  payment/src/data/seeders/transactionHistorySeeder.ts
  payment/src/server.ts
  payment/src/services/index.ts
  payment/src/services/payment/payment.ts
Labels: enhancement

#94 Add update validateuuid
  gateway/src/helpers/uuid.ts
Labels: enhancement

#53 Page of transactions list
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/index.ts
  frontend/src/common/enums/routes.ts
  frontend/src/common/types/index.tsx
  frontend/src/common/types/store/state.ts
  frontend/src/common/types/transactions/index.ts
  frontend/src/common/types/transactions/transactions.ts
  frontend/src/components/Routing/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/hooks/useAction.ts
  frontend/src/localization/locale-keys.d.ts
  frontend/src/providers/localization.tsx
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Wallet/FundsPage/index.tsx
  frontend/src/scenes/Wallet/FundsPage/styles.module.scss
  frontend/src/scenes/Wallet/Transactions/RenderCell.tsx
  frontend/src/scenes/Wallet/Transactions/actions.ts
  frontend/src/scenes/Wallet/Transactions/index.tsx
  frontend/src/scenes/Wallet/Transactions/mock.json
  frontend/src/scenes/Wallet/Transactions/react-table.d.ts
  frontend/src/scenes/Wallet/Transactions/reducer.ts
  frontend/src/scenes/Wallet/Transactions/sagas.ts
  frontend/src/scenes/Wallet/Transactions/styles.module.scss
  frontend/src/scenes/Wallet/Transactions/utils.ts
  frontend/src/services/transactions.ts
  frontend/src/styles/_vars.scss
  gateway/src/api/middlewares/authorization.ts
  gateway/src/api/middlewares/index.ts
  gateway/src/common/constants/whiteRouts.ts
Labels: enhancement, in progress

#60 Add use leave page.
  frontend/src/components/LeavePage/index.tsx
Labels: enhancement

#99 add spinner component| add property type to props
  frontend/src/components/LoaderWrapper/index.tsx
  frontend/src/components/LoaderWrapper/styles.module.scss
Labels: enhancement

#87 Add project page
  backend/package-lock.json
  backend/src/api/routes/project.ts
  backend/src/common/types/project/project.ts
  backend/src/data/entities/project.ts
  backend/src/data/migrations/1628873533429-addTablesRefresh.ts
  backend/src/data/repositories/project.ts
  backend/src/data/seed-data/donatesData.ts
  backend/src/data/seed-data/donatorsPrivilegeData.ts
  backend/src/data/seed-data/faqData.ts
  backend/src/data/seed-data/projectDonatorsPrivilegesData.ts
  backend/src/data/seed-data/projectsData.ts
  backend/src/data/seed-data/userProfileData.ts
  backend/src/data/seeders/donateSeeder.ts
  backend/src/data/seeders/donatorsPrivilegeSeeder.ts
  backend/src/data/seeders/faqSeeder.ts
  backend/src/data/seeders/index.ts
  backend/src/data/seeders/projectDonatorsPrivilegesSeeder.ts
  backend/src/services/project/project.ts
  backend/src/services/topic/topic.ts
  frontend/package-lock.json
  frontend/src/actions/index.ts
  frontend/src/common/enums/routes.ts
  frontend/src/common/types/index.tsx
  frontend/src/common/types/project/project.ts
  frontend/src/common/types/store/state.ts
  frontend/src/components/Routing/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/MainPage/reducer.ts
  frontend/src/scenes/ProjectPage/actions.ts
  frontend/src/scenes/ProjectPage/components/Body.tsx
  frontend/src/scenes/ProjectPage/components/Header.tsx
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/reducer.ts
  frontend/src/scenes/ProjectPage/sagas.ts
  frontend/src/scenes/ProjectPage/styles.module.scss
  frontend/src/services/project.ts
  gateway/package-lock.json
  gateway/package.json
  gateway/src/common/constants/whiteRouts.ts
  notification/package-lock.json
  payment/package-lock.json
  shared/package-lock.json
Labels: enhancement, in progress

#105 Rework Tabs component
  frontend/src/components/Tabs/Tab/index.tsx
  frontend/src/components/Tabs/TabTitle/index.tsx
  frontend/src/components/Tabs/index.ts
  frontend/src/components/Tabs/styles.module.scss
  frontend/src/components/Tabs/tab-item/index.tsx
  frontend/src/components/Tabs/tab-item/styles.module.scss
  frontend/src/components/Tabs/tabs/index.tsx
  frontend/src/components/Tabs/tabs/styles.module.scss
  frontend/src/components/TabsExample/index.tsx
Labels: enhancement

#101 Connect ProjectInfo component; Update interface
  frontend/src/common/types/project/project.ts
  frontend/src/scenes/ProjectPage/components/Header.tsx
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/styles.module.scss
Labels: enhancement

#113 add faqs to project page
  backend/src/data/repositories/project.ts
  frontend/package-lock.json
  frontend/src/common/types/project/project.ts
  frontend/src/components/Accordion/styles.module.scss
  frontend/src/scenes/ProjectPage/components/FAQ.tsx
  frontend/src/scenes/ProjectPage/index.tsx
  frontend/src/scenes/ProjectPage/styles.module.scss
Labels: enhancement

#103 add ProjectPrivilege component
  frontend/src/components/Main/index.tsx
  frontend/src/components/ProjectPrivilege/index.tsx
  frontend/src/components/ProjectPrivilege/styles.module.scss
Labels: enhancement

#88 Edit header
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.module.scss
  frontend/src/styles/_vars.scss
Labels: enhancement

#116 Update Trends Page style with new Header
  frontend/src/scenes/TrendsPage/styles.module.scss
Labels: enhancement

#84 feat/projects-page
  backend/package-lock.json
  backend/src/api/routes/project.ts
  backend/src/data/entities/userProject.ts
  backend/src/data/migrations/1629218372287-update_entities.ts
  backend/src/data/repositories/project.ts
  backend/src/data/seed-data/userProfileProjectData.ts
  backend/src/services/project/project.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/index.ts
  frontend/src/common/types/global.d.ts
  frontend/src/common/types/store/state.ts
  frontend/src/components/ProjectCard/index.tsx
  frontend/src/components/Routing/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/scenes/Projects/actions.ts
  frontend/src/scenes/Projects/components/Filters/index.tsx
  frontend/src/scenes/Projects/components/Filters/styles.module.scss
  frontend/src/scenes/Projects/components/Statistic/index.tsx
  frontend/src/scenes/Projects/components/Statistic/styles.module.scss
  frontend/src/scenes/Projects/index.tsx
  frontend/src/scenes/Projects/reducer.ts
  frontend/src/scenes/Projects/sagas.ts
  frontend/src/scenes/Projects/styles.module.scss
  frontend/src/services/projects.ts
  gateway/package-lock.json
  package-lock.json
  payment/package-lock.json
  shared/package-lock.json
  shared/src/common/enums/index.ts
  shared/src/common/enums/projectFilters.ts
Labels: enhancement

#117 Add ability for UserPage to display
  frontend/.eslintrc.json
  frontend/src/actions/index.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/OpenUserModalOption/index.tsx
  frontend/src/components/OpenUserModalOption/styles.module.scss
  frontend/src/components/Routing/index.tsx
  frontend/src/scenes/UserPage/actions.ts
  frontend/src/scenes/UserPage/reducer.ts
Labels: enhancement, in progress

#123 Fix Trends Page
  backend/src/common/types/project/index.ts
  backend/src/common/types/project/projectItem.ts
  backend/src/common/types/user/index.ts
  backend/src/data/repositories/project.ts
  frontend/src/services/projects.ts
Labels: hotfix

#129 Trends Page: Add labels
  frontend/src/common/constans/index.ts
  frontend/src/common/constans/length/index.ts
  frontend/src/common/constans/length/wordLength.ts
  frontend/src/components/Chart/index.tsx
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/style.module.scss
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/index.tsx
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/style.module.scss
  frontend/src/scenes/TrendsPage/components/ProjectsChart/index.tsx
  frontend/src/scenes/TrendsPage/components/ProjectsChart/style.module.scss
  frontend/src/scenes/TrendsPage/index.tsx
  frontend/src/scenes/TrendsPage/options/TagsOptions.ts
Labels: enhancement

#124 Feature comment
  frontend/package.json
  frontend/src/components/Comment/index.tsx
  frontend/src/components/Comment/styles.module.scss
  frontend/src/dictionaries/en.json
  frontend/src/dictionaries/ua.json
  frontend/src/localization/locale-keys.d.ts
  frontend/src/providers/localization.tsx
  frontend/src/services/date.ts
  frontend/src/styles/_vars.scss
Labels: enhancement

#134 Small fix Project Page
  frontend/package-lock.json
  frontend/src/scenes/ProjectPage/styles.module.scss
Labels: fix

#128 Update project query
  backend/src/common/types/project/index.ts
  backend/src/common/types/project/privilege.ts
  backend/src/common/types/project/privilegeWithBackersAmount.ts
  backend/src/common/types/project/project.ts
  backend/src/data/entities/index.ts
  backend/src/data/entities/team.ts
  backend/src/data/entities/teamUsers.ts
  backend/src/data/entities/userProfile.ts
  backend/src/data/mappers/index.ts
  backend/src/data/mappers/mapPrivileges.ts
  backend/src/data/migrations/1629373097347-updateUserProfile.ts
  backend/src/data/repositories/project.ts
  backend/src/data/seed-data/projectsData.ts
  backend/src/data/seed-data/teamData.ts
  backend/src/data/seed-data/teamUsersData.ts
  backend/src/data/seed-data/userProfileData.ts
  backend/src/data/seeders/index.ts
  backend/src/data/seeders/projectSeeder.ts
  backend/src/data/seeders/teamSeeder.ts
  backend/src/data/seeders/teamUsersSeeder.ts
  backend/src/services/project/project.ts
  frontend/src/services/project.ts
Labels: enhancement, in progress

#144 Fix Trends Page style
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
  frontend/src/scenes/TrendsPage/index.tsx
  frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
  frontend/src/scenes/TrendsPage/reducer.ts
Labels: fix

#137 Bug fix header
  frontend/package.json
  frontend/src/components/CardExample/styles.module.scss
  frontend/src/components/Comment/styles.module.scss
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.module.scss
  frontend/src/components/ProjectCard/styles.module.scss
  frontend/src/components/ProjectInfo/styles.module.scss
  frontend/src/scenes/Auth/SignupPage/styles.module.scss
  frontend/src/scenes/Auth/styles.module.scss
  frontend/src/scenes/CreateProject/components/Layout/styles.module.scss
  frontend/src/scenes/ProjectPage/styles.module.scss
  frontend/src/scenes/Projects/styles.module.scss
  frontend/src/scenes/TrendsPage/styles.module.scss
  frontend/src/scenes/UserPage/styles.module.scss
  frontend/src/scenes/Wallet/CustomFund/styles.module.scss
  frontend/src/scenes/Wallet/Fund/styles.module.scss
  frontend/src/scenes/Wallet/FundsPage/styles.module.scss
  frontend/src/styles/_mixins.scss
  frontend/src/styles/_vars.scss
Labels: fix

#145 update donators privilage
  backend/src/data/entities/donatorsPrivilege.ts
  backend/src/data/entities/index.ts
  backend/src/data/entities/project.ts
  backend/src/data/entities/projectDonatorsPrivilege.ts
  backend/src/data/migrations/1628360157794-AddTables.ts
  backend/src/data/migrations/1629714144944-AddTables.ts
  backend/src/data/migrations/1629724796604-update-DonatorPrivilege.ts
  backend/src/data/repositories/project.ts
  backend/src/data/seed-data/donatorsPrivilegeData.ts
  backend/src/data/seed-data/projectDonatorsPrivilegesData.ts
  backend/src/data/seeders/index.ts
  backend/src/data/seeders/projectDonatorsPrivilegesSeeder.ts
Labels: update

#148 Fix columns
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
  frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/style.module.scss
Labels: fix

#152 restore AddTables
  backend/src/data/migrations/1628360157794-AddTables.ts
  backend/src/data/migrations/1629714144944-AddTables.ts
Labels: update

#149 bug-fix-datepicker
  frontend/src/components/DatePicker/index.tsx
  frontend/src/scenes/Auth/SignupPage/components/form-additional.tsx
Labels: enhancement, hotfix

#169 Update UserProfile edit page
  frontend/src/scenes/UserPage/components/Header.tsx
  frontend/src/scenes/UserPage/styles.module.scss
Labels: enhancement
